### ISSUE TITLE
conf/config.yaml参数具体含义及获取途径

### ISSUE THREAD

**Issue by refiny** [dotbitHQ/das-account-indexer#2]
在试图运行indexer的过程中，出现如下错误：
2022-02-12 02:35:43.007007786   INFO    cmd/main.go:66  ▶ [main] db ok
2022-02-12 02:35:43.014012821   INFO    cmd/main.go:79  ▶ [main] ckb node ok
2022-02-12 02:35:43.207004849   FATAL   cmd/main.go:43  ▶ [main] InitDasSoScript err: ConfigCellDataBuilderByTypeArgs err: ConfigCellDataBuilderRefByTypeArgs err: ConfigCellMainFromSlice err: HeaderIsBroken ConfigCellMain 0 < 4

但不能定位到具体的错误原因及修正方式。烦请协助告知。

**Comment by refiny** [comment]
对于错误信息都响应得挺不友好的，只知道出错了，不知道处理措施。
2022-02-12 19:09:42.290148029   FATAL   cmd/main.go:43  ▶ [main] InitDasSoScript err: ConfigCellDataBuilderByTypeArgs err: ConfigCellDataBuilderRefByTypeArgs err: ConfigCellMainFromSlice err: FieldCountNotMatch

**Comment by scorpiotzh** [comment]
Hi, this error is running by which release version or branch? what's the configuration information in the file config.yaml?

**Comment by refiny** [comment]
My Local environment configuration file as below:
```java
server:
  net: 1 # 1-mainnet 2-testnet
  http_server_addr: ":8121"
  http_server_addr_indexer: ":8122"
  http_server_addr_reverse: ":8123"
chain:
  ckb_url: "http://127.0.0.1:8114"
  index_url: "http://127.0.0.1:8116"
  current_block_number: 4872287
  confirm_num: 4
  concurrency_num: 100
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "123456"
    db_name: "das_account_indexer"
    max_open_conn: 100
    max_idle_conn: 50
cache:
  redis:
    addr: "127.0.0.1:6379"
    password: ""
    db_num: 0
das_lib:
  thq_code_hash: "0x9e537bf5b8ec044ca3f53355e879f3fd8832217e4a9b41d9994cf0c547241a79"
  das_contract_args: "0xc126635ece567c71c50f7482c5db80603852c306"
  das_contract_code_hash: "0x00000000000000000000000000000000000000000000000000545950455f4944"
  map_das_contract:
    "config-cell-type": "0x3775c65aabe8b79980c4933dd2f4347fa5ef03611cef64328685618aa7535794"
    "account-cell-type": "0x96dc231bbbee6aa474076468640f9e0ad27cf13b1343716a7ce04b116ea18ba8"
    "balance-cell-type": "0xbdc8f42643ccad23e8df3d2e8dbdea9201812cd1b7f84c46e69b020529629822"
    "das-lock": "0xda22fd296682488687a6035b5fc97c269b72d7de128034389bd03041b40309c0"
    "reverse-record-cell-type": "0x000f3e1a89d85d268ed6d36578d474ecf91d8809f4f696dd2e5b97fe67b84a2e"
```

I am using the latest version v1.1.1 from source code.

**Comment by scorpiotzh** [comment]
Please try the new version v1.1.2
