### ISSUE TITLE
增加一个 DoH 接口用于返回 DWeb Records

### ISSUE THREAD

**Issue by livid** [dotbitHQ/das-account-indexer#6]
比如这是 ETH.LIMO 项目为 .eth 维护的 DoH 服务器：

https://dns.eth.limo/dns-query

如果发起一个这样的请求：

```
curl --http2 -H "accept: application/dns-json" "https://dns.eth.limo/dns-query?name=vitalik.eth"
```

就可以拿到这样的一个结果：

```
{
  "Status": "0",
  "RD": false,
  "RA": false,
  "AD": false,
  "CD": false,
  "TC": false,
  "Question": [
    {
      "type": 16,
      "name": "vitalik.eth"
    }
  ],
  "Answer": [
    {
      "type": 16,
      "name": "vitalik.eth",
      "data": "dnslink=/ipfs/QmWxRwMg3bHyJxfAuPnUky2yNgNt51qmZqC99Ffenjxa94/",
      "ttl": 600
    }
  ]
}
```

如果 .bit 的 Indexer HTTP Server 上也有这样的一个可以把 DWeb Record 返回为 TXT DNSLink 的服务器，那么把这个服务器配置进 Kubo，Kubo 就可以实现用 IPFS Gateway 解析和访问 .bit 上的 IPFS DWeb 网站。

相关文档：

https://blog.v2ex.com/EA7C9A0D-133C-4416-9C55-919AB7350FCC/

**Comment by livid** [comment]
比如 V2EX 的 IPFS Gateway 上配置了 .eth 的 DoH 服务器之后，就可以支持这样的效果：

https://ipfs.v2ex.pro/ipns/olivida.eth/

**Comment by paicha** [comment]
增加 DoH 接口还可以给 [Kubo](https://github.com/ipfs/kubo/blob/d82dec32482bb4ece33d3e867c4f615eea6bb487/core/node/dns.go#L18) 提 PR，合并进去的话，也会吸引到更多的社区支持。

**Comment by scorpiotzh** [comment]
非常好的提议，目前也在排期中。当然，如果有开发者感兴趣也可以给我们提 PR。

**Comment by livid** [comment]
看到这个 issue 被标记为 completed 了，是这个功能现在已经有了吗？
