### ISSUE TITLE
Breaking change in your API

### ISSUE THREAD

**Issue by livid** [dotbitHQ/das-account-indexer#9]
It seems recently these are changed in your API:

errno -> err_no
errmsg -> err_msg

It breaks apps that rely on these fields.

Also, all of the documentation is still using `errno` and `errmsg`:

https://github.com/dotbitHQ/das-account-indexer/blob/main/API.md#get-account-basic-info

**Comment by scorpiotzh** [comment]
We are very sorry, this was an oversight on our part and we have fixed the issue!
Both fields will be supported for now, but the "errno" and "errmsg" fields will be removed in the future.
